<!DOCTYPE html>
<html>
<head>
<title> first site </title>
<style>
input{padding:20px;
margin:20px}
</style>
</head>
<body>
<!------form start------>
<form action="gallery.html" target="_blank">

<input type="text" name="frame" placeholder="name">
</br>

<input type="text" name="age" placeholder="age">
</br>
<input type="radio" name="gender" id="male">
<label for="male">male</label>
</br>
<input type="radio" name="gender" id="female">
<label for="female">female</label>
</br>
<input type="button" value="button">
<input type="submit" value="register">




</form>
<!------form <form end------>

</body>
</html>
